import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-input-button-unit',
  templateUrl: './input-button-unit.component.html',
  styleUrls: ['./input-button-unit.component.scss'],
})
export class InputButtonUnitComponent implements OnInit {
  title: string = 'Hello World!';

  generateTitle(): string {
    return 'generated by a method.';
  }
  constructor() {}
  ngOnInit(): void {}
  
  changeTitle(newTitle: string): void {
    this.title = newTitle;
  }
  getInputValue(event: Event) {
    return (event.target as HTMLInputElement).value;
  }
}
